# -*- coding: utf-8 -*-
"""Source Code.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VX1U70zJ44XxOiRBqXWgQyVg4cM-49Ew
"""

import random
import math
import matplotlib.pyplot as plt

ra1 = 2
rb1 = -1
ra2 = 1
rb2 = -1 
pm = 1/10

def kromosom():
  kromosom = []
  for i in range(10):
    kromosom.append(random.randint(0,1))
  return kromosom

def populasi():
  populasi = []
  for i in range(10):
    populasi.append(kromosom())
  return populasi

def dekodeKro(x,batas_atas,batas_bawah):
  hasil = 0
  sum = 0
  for i in range(len(x)):
    hasil += 2**(-i-1)
    sum += x[i]*2**(-i-1)
  result = batas_bawah + (batas_atas - batas_bawah)/hasil * sum
  return result

def fungsi(x):
  hasil = math.cos(x[0])*math.sin(x[1])-(x[0]/x[1]**2+1)
  return hasil

def fitness(h):
  a = 0.1
  hasil = 1/(h + a)
  return hasil

def probabilitas(f):
  hasil = 0 
  proArr = []
  for i in f:
    jumlah = i/sum(f)
    proArr.append(jumlah)
  return proArr

def roulette(kro,pro):
  rouArr = []
  for i in range(len(kro)):
    acak = random.random()/10
    if acak < pro[i]:
      rouArr.append(kro[i])
  return rouArr

def crossover(kro):
  anakArr = []
  for i in range(5):
    orangtua1 = kro[random.randint(0,len(kro)-1)]
    orangtua2 = kro[random.randint(0,len(kro)-1)]
    titik_potong = random.randint(0,9)
    anak1 = orangtua1[0:titik_potong] + orangtua2[titik_potong:]
    anak2 = orangtua2[0:titik_potong] + orangtua1[titik_potong:]
    anakArr.append(anak1)
    anakArr.append(anak2)
  return anakArr

# def total_fitness(f):
#   hasil = 0
#   for i in range(10):
#     hasil += f
#   return hasil

def mutasi(anak):
  total_mutan = []
  for i in anak:
    a = random.random()
    mutan = []
    for j in i :
      if a <= pm :
        if j == 0:
          mutan.append(1)
        else:
          mutan.append(0)
      else:
        mutan.append(j)
    total_mutan.append(mutan)
  return total_mutan

def seleksi():
  for i in range(len(f)) :
    for j in range(len(f_anak)):
      if f_anak[j] > f[i]:
        f[i] = f_anak[j]
        a[i] = mutAnak[j]
        x[i] = x_anak[j] 
        break
  return a

# main
a = populasi()
x = []
p = []
f = []
sumF = []

for i in range(20):
  print('')
  print('================================================== GENERASI ' + str(i) + ' ===================================================================')
  print('')
  print('Populasi')
  print(a)
  print('x1,x2')
  for i in a :
    x.append([dekodeKro(i[:5],ra1,rb1),dekodeKro(i[5:],ra2,rb2)])
  print(x)
  print('')

  print('Fitness')
  for i in x:
    f.append(fitness(fungsi(i)))
  print(f)
  print('')

  print('Probabilitas')
  p = probabilitas(f)
  print(p)
  print('')

  print('Orang Tua Terpilih')
  parent = roulette(a,p)
  print(parent)
  print('')

  print('Crossover')
  anak = crossover(parent)
  print(anak)
  print('')

  print('Mutasi Anak')
  mutAnak = mutasi(anak)
  print(mutAnak)
  print('')

  print('X anak')
  x_anak = []
  for i in mutAnak:
    x_anak.append([dekodeKro(i[:5],ra1,rb1),dekodeKro(i[5:],ra2,rb2)])
  print(x_anak)
  print('')


  print('Fitness Anak')
  f_anak = []
  for i in x_anak:
    f_anak.append(fungsi(i))
  print(f_anak)
  print('')

  print('Seleksi')
  print(seleksi())
  sumF.append(sum(f))
  x_anak = []
  f_anak = []
  x = []
  f = []  
  # f = []
  # p = []
print(sumF)
plt.plot(sumF)

# print(populasi())

# a = populasi()
# x = []
# f = []
# p = []
# print(a)
# for i in a:
#   x.append([dekodeKro(i[:5],ra1,rb1),dekodeKro(i[5:],ra2,rb2)])
# print(x)
# print(x[0])
# for i in x:
#   f.append(fitness(fungsi(i)))
# print(f)
# print('Dibawah probablitas')
# p = probabilitas(f)
# print(p)


# for i in range(populasi()):
#   print(dekodeKro(genotip(kromosom([i])),ra1,rb1))

# print(len(a))
# print(len(p))
# parent = roulette(a,p)
# print(parent)

# print(parent[0][0:3]+parent[1][1:2])
# anak = crossover(parent)
# print(anak)

# mutAnak = mutasi(anak) 
# print(mutAnak)
# x_anak = []
# for i in mutAnak:
#   x_anak.append([dekodeKro(i[:5],ra1,rb1),dekodeKro(i[5:],ra2,rb2)])
# print(x_anak)

# print('Fitness anak')
# f_anak = []
# for i in x_anak:
#   f_anak.append(fungsi(i))
# print(f_anak)

# print(a)
# print(mutAnak)
# print(seleksi())

